version: 2.1
parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""


orbs:
  win: circleci/windows@2.2.0 

workflows:
  when: << pipeline.parameters.GHA_Action >>
  main:
    jobs:
      - build

jobs:
  build:
    executor:
      name: win/default
      version: edge
      shell: cmd.exe
    steps:
      - checkout
      - run: echo Hello World
          
      
