version: 2.1 

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: 'windows-server-2019-vs2019:edge'
      resource_class: windows.large
      shell: powershell.exe -ExecutionPolicy Bypass
    steps:
      - checkout
      - run: python --version
      
          
      
