version: 2.1

jobs:
  build:
    machine:
      image: 'windows-server-2019-cuda:stable'
      resource_class: windows.gpu.nvidia.medium
      shell: powershell.exe -ExecutionPolicy Bypass
    steps:
      - run: Write-Host 'Hello, Windows'
  
