version: 2.1

orbs:
  win: circleci/windows@2.3.0 

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    executor:
      name: win/default
      version: internal
      shell: cmd.exe
    steps:
      - checkout
      - run: python -V
      - run: py --list
          
      
