version: 2.1
jobs:
  build-windows:
    machine:
      image: windows-server-2022:current
      resource_class: windows.medium
      shell: powershell.exe -ExecutionPolicy Bypass
    steps:
      - run: echo 'test'
