version: 2.1
orbs:
  win: circleci/windows@4.0
jobs:
  build:
    executor:
      name: win/server-2022
      version: internal
      variant: gui
    steps:
       - run: ssh -V
workflows:
   my-workflow:
      jobs:
        - build

      
