  version: 2.1

  jobs:
    build:
      machine:
        image: 'windows-server-2022-gui:edge'
        resource_class: windows.large
        shell: powershell.exe -ExecutionPolicy Bypass
      steps:
        - run: Write-Host 'Hello, Windows'
  
