version: 2.1
orbs:
  win: circleci/windows@4.1
jobs:
  build:
    executor: 
      name: win/server-2022
      version: internal
    steps:
      - run: nvm --version
workflows:
  my-workflow:
    jobs:
      - build
  
