version: 2.1

workflows:
  build-and-unittest:
    jobs:
      - build-windows

jobs:
  build-windows:
    machine:
      #image: windows-server-2019-cuda:current
      # image: windows-server-2019-vs2019:current
      image: windows-server-2022-gui:edge
      #resource_class: windows.gpu.nvidia.medium
      resource_class: windows.medium
      shell: powershell.exe -ExecutionPolicy Bypass
      #docker_layer_caching: true
    steps:
      - run:
          name: set env var
          command: |
            setx MICHAEL ROTHSTEIN /M
            refreshenv
          shell: cmd.exe
      - run:
          name: get env var
          command: Get-ItemPropertyValue 'registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment' MICHAEL
      - run:
          name: Print var
          shell: cmd.exe
          environment:
            APP_VERSION: 1.2.3
          command: |

            setx SHA1 %CIRCLE_SHA1%
            "%SHA1%"

            # echo $sha1
            REM $tempvar = "APP_VERSION_$sha1"
            REM $tempvalue = $env:tempvar
            REM echo $tempvalue
            REM setx targetvar $tempvalue /m
