version: 2.1

orbs:
  win: circleci/windows@2.2.0 

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    executor:
      name: win/default
      version: internal
    steps:
      - checkout
      - run: node --version
      - run: go version
      - run: ls
      
