version: 2.1

orbs:
  win: circleci/windows@2.2.0 

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    executor:
      name: win/default
      version: edge
    steps:
      - checkout
      - run: git clone git@github.com:beatcracker/VSCELicense.git
      - run:
          name: update VS timeout value.
          shell: powershell.exe
          command: |
            $currentDir = Get-Location
            Write-Output "Directory is: $currentDir"
            Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
            $schAction = New-ScheduledTaskAction -Execute "Powershell.exe" -Argument '-NoProfile -WindowStyle Hidden -File "C:\Users\circleci\project\scripts\VSLicense.ps1"'
            $schTrigger = New-ScheduledTaskTrigger -AtStartup
            $schPrincipal = New-ScheduledTaskPrincipal -UserId "NT AUTHORITY\SYSTEM" -LogonType ServiceAccount
            Register-ScheduledTask -Action $schAction -Trigger $schTrigger -TaskName "vstest" -Description "Scheduled Task to run vs  configuration Script At Startup" -Principal $schPrincipal
     
