version: 2.1

workflows:
  build-and-unittest:
    jobs:
      - build-windows

jobs:
  build-windows:
    machine:
      image: windows-server-2019-nvidia-medium:current
      resource_class: large
      shell: powershell.exe -ExecutionPolicy Bypass
      docker_layer_caching: true
    steps:
      - run: docker version
      - run:
          name: Install Test converter
          command: dotnet tool install --tool-path . dotnetsay
          shell: cmd.exe
      - run:
          name: test tool
          command: .\dotnetsay
          shell: cmd.exe