version: 2.1

orbs:
  win: circleci/windows@2.3.0 

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    executor:
      name: win/gpu-nvidia
      version: stable
      shell: cmd.exe
    steps:
      - checkout
      - run: echo Hello World!
          
      
