version: 2.1

workflows:
  build-and-unittest:
    jobs:
      - build

jobs:
  build:
    machine:
      image: windows-server-2022-gui:edge
      docker_layer_caching: true
    steps:
      - checkout