jobs:
  build:
    docker:
     - image: mcr.microsoft.com/dotnet/nightly/sdk:6.0


    steps:
      - run: |
          echo '#!/bin/sh' > run.sh
          echo 'echo Hello world!' >> run.sh
          chmod +x run.sh
      - run: ./run.sh