version: 2.1 

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    machine:
      image: 'windows-server-2022-vs2022:internal'
      resource_class: windows.large
      shell: powershell.exe -ExecutionPolicy Bypass
    steps:
      - checkout
      - run: python --version
          
      
