version: 2.1
orbs:
  win: circleci/windows@5.0 
  version: edge
jobs:
  build:
    executor: win/server-2022
    steps:
      - run: Write-Host 'Hello, Windows'
workflows:
  my-workflow:
    jobs:
      - build