version: 2.1

workflows:
  build-and-unittest:
    jobs:
      - build-windows

jobs:
  build-windows:
    machine:
      #image: windows-server-2019-cuda:previous
      #image: windows-server-2019-vs2019:stable
      image: windows-server-2022-gui:current
      #resource_class: windows.gpu.nvidia.medium
      resource_class: windows.medium
      shell: powershell.exe -ExecutionPolicy Bypass
      #docker_layer_caching: true
    steps:
      - run:
          name: get env var.
          command: |
            $sha1 = $env:CIRCLE_SHA1
            $tempvar = "APP_VERSION_$sha1"
            $tempvar
            [System.Environment]::SetEnvironmentVariable("TEMPVAR",$tempvar,[System.EnvironmentVariableTarget]::MACHINE)
      - run:
          name: get env var.
          command: |
             Get-ItemPropertyValue 'registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment' $TEMPVAR