version: 2.1

workflows:
  build-and-unittest:
    jobs:
      - build-windows

jobs:
  build-windows:
    machine:
      #image: windows-server-2019-cuda:current
      # image: windows-server-2019-vs2019:current
      image: windows-server-2022-gui:edge
      #resource_class: windows.gpu.nvidia.medium
      resource_class: windows.medium
      shell: powershell.exe -ExecutionPolicy Bypass
      #docker_layer_caching: true
    steps:
      - run:
          name: set env var
          command: |
            setx MICHAEL ROTHSTEIN /M
            refreshenv
          shell: cmd.exe
      - run:
          name: get env var
          command: Get-ItemPropertyValue 'registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment' MICHAEL
      - run:
          name: Print var
          environment:
            APP_VERSION: 1.2.3
          command: |

            $APP_VERSION_NAME = "APP_VERSION_$env:CIRCLE_SHA1"
            [System.Environment]::SetEnvironmentVariable('APP_VERSION',$APP_VERSION_NAME,[System.EnvironmentVariableTarget]::Machine)
            refreshenv
            gci env:
