version: 2.1

jobs:
  build:
    machine:
      image: 'windows-server-2022-gui:edge'
      resource_class: windows.gpu.nvidia.medium
      shell: powershell.exe -ExecutionPolicy Bypass
    steps:
      - run: docker
  
