version: 2.1
orbs:
  win: circleci/windows@4.0
jobs:
  build:
    executor: win/server-2022
    version: "internal"
    variant: "gui"
    steps:
       - run: Write-Host 'Hello, Windows..'
workflows:
   my-workflow:
      jobs:
        - build
      
          
      
