on: [push]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Pipeline
        id: citrigger
        uses: KyleTryon/GHA_Trigger_For_CCI@v2.10
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}