on: [push]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Pipeline
        id: citrigger
        uses: https://github.com/KyleTryon/GHA_Trigger_For_CCI/tags
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}